### ISSUE TITLE
ftrobopy crashing after undefined time

### ISSUE THREAD

**Issue by olagino** [ftrobopy/ftrobopy#10]
My program runs quite normal for at least 1-2mins without any problems. But then I get following Traceback (the version of ftrobopy is the standard on the community-firmware on 0.9.2-3 or rather 0.98):
```
Traceback (most recent call last):
File "script.py", line [...], in [...]
    sensor = self.io.input(n).state()
  File "[...]/ftrobopy.py", line 1663, in input
    self.updateConfig()
  File "[...]/ftrobopy.py", line 432, in updateConfig
   buf = struct.pack('<Ihh B B 2s BBBB BB2s BB2s BB2s BB2s BB2s BB2s BB2s BB2s B3s B3s B3s B3s 16h', *fields)
struct.error: short format requires (-0x7fff - 1) <= number <= 0x7fff
```
The communication to the TXTs IOs is put into execution via following lines:
```
    self.io = ftrobopy.ftrobopy("127.0.0.1",65000)
    sensor = self.io.input(1).state()
```

**Comment by ftrobopy** [comment]
The reason seems to be an overflow of the config_id value which happens if updateConfig() is called too often, e.g. the configuration of the inputs and outputs of the TXT is changed frequently. The ROBOProLib expects a 2 byte short value (range -0x7fff to 0x7fff) here, coded by 'h' in the struct.pack format string.

This is a bug in ftrobopy and I will commit a fix for that.

**Comment by ftrobopy** [comment]
Issue has been fixed
