### ISSUE TITLE
Support for I2C

### ISSUE THREAD

**Issue by otfried** [ftrobopy/ftrobopy#8]
Is it possible to use I2C sensors and actuators, like in RoboPro?   I couldn't find anything in the documentation or the source files.

I didn't find anything about I2C in Fischertechnik's `TXT-C-Programming-Kit-4-1-6`, so maybe there is no documentation on how I2C can be implemented?

**Comment by ftrobopy** [comment]
fischertechnik has not yet released any documentation or source code on the i2c interface API of RoboPro. I will implement i2c support into ftrobopy as soon as this information is public.

**Comment by ftrobopy** [comment]
There may be another way of supporting i2c on the TXT in offline/download mode by directly accessing the linux i2c drivers. I currently have no external i2c device available and cannot test this.

**Comment by chehr** [comment]
If this is the Issue, I can  organize a i2c device to you, Thorsten? Hope this helps for i2c Python Support.

**Comment by ski7777** [comment]
I²C is already working via the standard linux I²C tools. You need to know that you have to use dev 1 instead of 0. In my ftcommunity-apps repository you can see two I²C demos for the TXT. I think that I²C should not be part of ftrobopy because it is not related to the TXT.

Raphael

**Comment by ftrobopy** [comment]
@Raphael: the method you describe only works in 'download' or 'direct' mode with the community firmware.

I think, it would be useful to have I²C support in ftrobopy to support 'online' mode and the original fischertechnik firmware as well. For this I would need the description of the I²C-ROBOPro tcp/socket protocol. I still hope that fischertechnik will publish this at some point. Currently I have no time to reverse engineer the protocol myself.

@chehr: thank you for your offer but I don't need it. Meanwhile I have an I²C-device myself that I could use.

**Comment by ski7777** [comment]
I would suggest to add a smbus2-like API. https://github.com/kplindegaard/smbus2
When running online mode ftrobopy should manage the i2c connection and when running direct mode, ftrobopy should just create the smbus2 bus class.

Raphael

P.s. I will try to implement smbus2-like API in my https://github.com/ski7777/fttxpy project

**Comment by ftrobopy** [comment]
After a little bit of reverse engineering the first (experimental) implementation of I2C in ftrobopy (version >= 1.88) is available. It works in "Online"- and "Download"-mode (but not yet in "direct"-mode).
See examples/i2c_bmx055_acct.py and manual.pdf for further info on new "i2c_read" and "i2c_write" commands.

**Comment by ski7777** [comment]
Very good! In direct mode, we can just use the i2c-1 bus of linux. You should try to provide teh same interface. My approach would be to implement an smbus2-like interface for "online"-mode.

**Comment by ski7777** [comment]
As mentioned https://forum.ftcommunity.de/viewtopic.php?f=33&t=3429&p=37061#p37061 I will try to create a system to allow access to all types of controllers. There I will implement the ftrobopy i2c api. To make things easier, it would be really nice to use standardized interfaces everywhere. Currently I don´t have i2c support in github.com/ski7777/fttxpy but someday I will implement it with a smbus2-like interface.

The new I/O server will also provide smbus2-like objects for every accessible i2c bus.

**Comment by dfquiroga** [comment]
Hi, i'm trying to use library into the TXT but i got this error:
"....
ftrobopy.py", line 398, in i2c_write
    res          = self._i2c_sock.send(buf)
..."

any idea?

**Comment by ftrobopy** [comment]
Hi, could you please post the complete error message ?
Are you using the original fischertechnik firmware (which version ?) or the community firmware (which version ?) on the TXT ? 
Are you running the python script on the TXT in offline mode or on a PC in online mode ?

**Comment by dfquiroga** [comment]
Thanks, this is the error:

 txt.i2c_write(0x18, 0x3e, 0x80)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/knobloch/PYTHONTEST/ftrobopy.py", line 398, in i2c_write
    res          = self._i2c_sock.send(buf)
BrokenPipeError: [Errno 32] Broken pipe


this error appears in the original firmware version 4.4.4 and ronning in console in using ssh connection to the TXT and connected as localhost to the io server.

the version of library is the 1.88, with 1.80 i got a non method exist error.

**Comment by ftrobopy** [comment]
Thanks for the detailed information.

Short answer: it is (currently) not possible to use i2c commands in ftrobopy in an interactive python console.

The reason for this is that the TXT will automatically stop its i2c server process if i2c communication is quiet for longer than 2 seconds. You would need to type very fast in an interactive python session to stay within this 2 sec. limit.
(by the way: ROBOPro shows the same behaviour. If no i2c-commands are sent for longer than 2 seconds i2c stops working until the ROBOPro-programm is restarted).

A workaround would be to have a background process running which continuously (interval < 2 sec.) sends some i2c command that does not have any side effects. I would have implemented that into ftrobopy but since I am no i2c expert I didn't know which i2c command could be continuously sent without compromising overall i2c communication. ROBOPro also doesn't have such a background process (at least I couldn't find one).

I am open for ideas here. Specifically: which i2c command could be used for that purpose ?

**Comment by XyBrot** [comment]
Hi, 
I use the cfw with ftrobopy 1.88  on my TXT controller. Now I want to write something with the NFC reader delievered with the FT-training factory (connected with the i2c bus) to a NFC chip. I wrote a python programm that should write something to the chip by clicking on a button on the TXT.

But I get the following:
Traceback (most recent call last):
  File "/opt/ftc/apps/user/191fe5a6-313b-4083-af65-d1ad7fd6d281/vgr.py", line 221, in on_button_clicked
    self.txt.i2c_write(0x24, 0x3e, 0x80)
  File "/home/ftc/apps/191fe5a6-313b-4083-af65-d1ad7fd6d281/ftrobopy.py", line 413, in i2c_write
    res          = self._i2c_sock.send(buf)
AttributeError: 'ftrobopy' object has no attribute '_i2c_sock'

I built the cfw by my own, so I could replace the ftrobopy with the latest version 1.94 but same issue.

Can anyone help me?
Thanks and best regards

**Comment by ftrobopy** [comment]
Currently ftrobopy does not support I2C in 'direct'-mode (which is the default when startet in the cfw) but only in 'online'-mode.

In order to enforce 'online'-mode (even when running locally on the TXT) you need to initialise ftrobopy with '127.0.0.1' (instead of 'auto' or nothing)

Also make sure that the cfw-app "FT-GUI" has been started. Please have a look at https://forum.ftcommunity.de/viewtopic.php?f=33&t=6115#p46156 for further details on how to start the app automatically in your python-script.

It is also possible to just use the standard i2c python library ("import sambus") which is included in the cfw. FT-GUI and 'online'-mode are not needed then.

**Comment by IJMTutorSES** [comment]
How to get the newest version of ftrobopy? i can only install version 1.8

**Comment by ftrobopy** [comment]
To get the newest ftrobopy version (currently this is 1.97) simply clone it from github.com, e.g. 
  git clone https://github.com/ftrobopy/ftrobopy.git
Then copy the file ftrobopy/ftrobopy.py into your python site-packages folder or into the folder where your python scripts reside.
